export const defaultProducts = [
    {
        id: 1,
        nombre: "Hollow Knight: Silksong",
        precio: 7990,
        descripcion: "Secuela del aclamado Hollow Knight. Los jugadores controlan a Hornet en un reino desconocido lleno de desafíos y secretos.",
        imagen: "assets/Silksong_cover.webp",
        categoria: ["Acción", "Aventura", "Indie"],
        plataforma: ["PC", "Playstation", "Xbox", "Nintendo Switch"],
        cantidad: 1,
        stock: 25,
    },
    {
        id: 2,
        nombre: "Elden Ring",
        precio: 49990,
        descripcion: "Un épico RPG de acción de mundo abierto de FromSoftware y George R.R. Martin, lleno de jefes desafiantes y misterios.",
        imagen: "assets/EldenRing_cover.jpg",
        categoria: ["Acción", "RPG", "Mundo Abierto"],
        plataforma: ["PC", "Playstation", "Xbox"],
        cantidad: 1,
        stock: 12,
    },
    {
        id: 3,
        nombre: "Celeste",
        precio: 5990,
        descripcion: "Un desafiante juego indie de plataformas sobre la superación personal mientras escalas la montaña Celeste.",
        imagen: "assets/Celeste_cover.png",
        categoria: ["Plataformas", "Indie", "Aventura"],
        plataforma: ["PC", "Playstation", "Xbox", "Nintendo Switch"],
        cantidad: 1,
        stock: 30,
    },
    {
        id: 4,
        nombre: "The Legend of Zelda: Breath of the Wild",
        precio: 39990,
        descripcion: "Explora libremente el vasto reino de Hyrule en esta innovadora entrega de la saga Zelda.",
        imagen: "assets/BreathOfTheWild_cover.webp",
        categoria: ["Acción", "Aventura", "Mundo Abierto"],
        plataforma: ["Nintendo Switch", "Wii U"],
        cantidad: 1,
        stock: 8,
    },
    {
        id: 5,
        nombre: "Stardew Valley",
        precio: 6990,
        descripcion: "Simulador de granja y vida rural, donde puedes cultivar, criar animales, pescar y formar relaciones.",
        imagen: "assets/StardewValley_cover.png",
        categoria: ["Simulación", "Indie", "RPG"],
        plataforma: ["PC", "Playstation", "Xbox", "Nintendo Switch", "Móvil"],
        cantidad: 1,
        stock: 40,
    },
    {
        id: 6,
        nombre: "God of War: Ragnarök",
        precio: 59990,
        descripcion: "Kratos y Atreus continúan su viaje en los Nueve Reinos enfrentándose a dioses nórdicos.",
        imagen: "assets/GodOfWarRagnarok_cover.webp",
        categoria: ["Acción", "Aventura", "RPG"],
        plataforma: ["Playstation", "PC"],
        cantidad: 1,
        stock: 15,
    },
    {
        id: 7,
        nombre: "Cuphead",
        precio: 9990,
        descripcion: "Juego de plataformas y disparos con estética de dibujos animados de los años 30 y dificultad elevada.",
        imagen: "assets/Cuphead_cover.webp",
        categoria: ["Plataformas", "Acción", "Indie"],
        plataforma: ["PC", "Xbox", "Playstation", "Nintendo Switch"],
        cantidad: 1,
        stock: 22,
    },
    {
        id: 8,
        nombre: "Undertale",
        precio: 4990,
        descripcion: "RPG indie único donde tus decisiones importan y puedes ser pacifista o agresivo.",
        imagen: "assets/Undertale_cover.jpg",
        categoria: ["RPG", "Indie", "Aventura"],
        plataforma: ["PC", "Playstation", "Nintendo Switch"],
        cantidad: 1,
        stock: 18,
    },
    {
        id: 9,
        nombre: "Red Dead Redemption 2",
        precio: 39990,
        descripcion: "Un épico western de mundo abierto con una historia cinematográfica y detallado mundo vivo.",
        imagen: "assets/RDR2_cover.jpg",
        categoria: ["Acción", "Aventura", "Mundo Abierto"],
        plataforma: ["PC", "Playstation", "Xbox"],
        cantidad: 1,
        stock: 10,
    },
    {
        id: 10,
        nombre: "Minecraft",
        precio: 19990,
        descripcion: "Juego de construcción y supervivencia en un mundo abierto hecho de bloques infinitos.",
        imagen: "assets/Minecraft_cover.jpeg",
        categoria: ["Sandbox", "Supervivencia", "Creatividad"],
        plataforma: ["PC", "Consolas", "Móvil"],
        cantidad: 1,
        stock: 50,
    },
    {
        id: 11,
        nombre: "The Witcher 3: Wild Hunt",
        precio: 29990,
        descripcion: "Un RPG épico donde controlas a Geralt de Rivia en un vasto mundo lleno de monstruos y misiones.",
        imagen: "assets/Witcher3_cover.jpg",
        categoria: ["RPG", "Acción", "Aventura"],
        plataforma: ["PC", "Playstation", "Xbox", "Nintendo Switch"],
        cantidad: 1,
        stock: 14,
    },
    {
        id: 12,
        nombre: "Hades",
        precio: 12990,
        descripcion: "Roguelike de acción donde juegas como Zagreus, hijo de Hades, tratando de escapar del inframundo.",
        imagen: "assets/Hades_cover.jpg",
        categoria: ["Acción", "Roguelike", "Indie"],
        plataforma: ["PC", "Playstation", "Xbox", "Nintendo Switch"],
        cantidad: 1,
        stock: 28,
    },
    {
        id: 13,
        nombre: "Dark Souls III",
        precio: 34990,
        descripcion: "Un RPG desafiante con combates intensos, escenarios oscuros y jefes imponentes.",
        imagen: "assets/DarkSouls3_cover.jpg",
        categoria: ["Acción", "RPG", "Soulslike"],
        plataforma: ["PC", "Playstation", "Xbox"],
        cantidad: 1,
        stock: 9,
    },
    {
        id: 14,
        nombre: "Animal Crossing: New Horizons",
        precio: 34990,
        descripcion: "Crea y personaliza tu isla en este relajante simulador social.",
        imagen: "assets/ACNH_cover.jpg",
        categoria: ["Simulación", "Social", "Creatividad"],
        plataforma: ["Nintendo Switch"],
        cantidad: 1,
        stock: 17,
    },
    {
        id: 15,
        nombre: "Sekiro: Shadows Die Twice",
        precio: 39990,
        descripcion: "Juego de acción de FromSoftware ambientado en un Japón mítico con combates de samuráis.",
        imagen: "assets/Sekiro_cover.webp",
        categoria: ["Acción", "Aventura", "Soulslike"],
        plataforma: ["PC", "Playstation", "Xbox"],
        cantidad: 1,
        stock: 11,
    },
    {
        id: 16,
        nombre: "Super Mario Odyssey",
        precio: 34990,
        descripcion: "Aventura de Mario en mundos coloridos usando su gorra mágica Cappy.",
        imagen: "assets/MarioOdyssey_cover.jpg",
        categoria: ["Plataformas", "Aventura", "Familiar"],
        plataforma: ["Nintendo Switch"],
        cantidad: 1,
        stock: 20,
    },
    {
        id: 17,
        nombre: "Dead Cells",
        precio: 9990,
        descripcion: "Roguelike de acción y plataformas con combates fluidos y rejugabilidad infinita.",
        imagen: "assets/DeadCells_cover.jpg",
        categoria: ["Acción", "Plataformas", "Roguelike"],
        plataforma: ["PC", "Playstation", "Xbox", "Nintendo Switch"],
        cantidad: 1,
        stock: 25,
    },
    {
        id: 18,
        nombre: "Cyberpunk 2077",
        precio: 44990,
        descripcion: "RPG de mundo abierto futurista ambientado en Night City, con narrativa profunda y exploración.",
        imagen: "assets/Cyberpunk2077_cover.jpg",
        categoria: ["RPG", "Acción", "Mundo Abierto"],
        plataforma: ["PC", "Playstation", "Xbox"],
        cantidad: 1,
        stock: 13,
    },
    {
        id: 19,
        nombre: "Ori and the Will of the Wisps",
        precio: 14990,
        descripcion: "Hermoso juego de plataformas y aventura con una historia emotiva y animaciones fluidas.",
        imagen: "assets/Ori2_cover.jpg",
        categoria: ["Plataformas", "Aventura", "Indie"],
        plataforma: ["PC", "Xbox", "Nintendo Switch"],
        cantidad: 1,
        stock: 19,
    },
    {
        id: 20,
        nombre: "Persona 5 Royal",
        precio: 39990,
        descripcion: "Un JRPG aclamado por su estilo artístico, personajes memorables y combates estratégicos.",
        imagen: "assets/Persona5R_cover.jpg",
        categoria: ["RPG", "JRPG", "Aventura"],
        plataforma: ["Playstation", "PC", "Xbox", "Nintendo Switch"],
        cantidad: 1,
        stock: 16,
    }
];

export function getProducts() {
    const saved = localStorage.getItem("products");
    return saved ? JSON.parse(saved) : defaultProducts;
}

export function saveProducts(products) {
    localStorage.setItem("products", JSON.stringify(products));

    //Para borrar el carrito al actualizar los productos
    localStorage.removeItem("cart");
}